### ISSUE TITLE
Dead link to to itch.io

### ISSUE THREAD

**Issue by nielsle** [sean-clayton/two-swords#1]
The meta data file of this repository contains a dead link to itch.io

https://github.com/sean-clayton/two-swords/blob/main/metadata.toml

https://seanclayton.itch.io/two-swords

<img width="227" alt="image" src="https://github.com/user-attachments/assets/8583d457-a751-4ba0-bc43-0952cfd2ae9a">

**Comment by sean-clayton** [comment]
Nice eye! I disabled the itch link while this was still in development. If you are looking for a pdf to download you can find them in the release section of the repository. I will add a comment in the metadata file to indicate that the link doesn't work at the moment, though!

**Comment by nielsle** [comment]
Thank you for he pointer. Typst looks lie a great tool for formatting rpgs.

**Comment by sean-clayton** [comment]
> Thank you for he pointer. Typst looks like a great tool for formatting rpgs.

It is! I'm closing this for now, but I will be sure to let you know when the itch page is back up :)
